### PR TITLE
Add Line-A functions

### PR DESCRIPTION
**Pull request by rosenrost**

### CODE REVIEW

**Comment by th-otto** [comment]
LineA is deprecated since TOS version 1.00. For what project do you need those?

**Comment by rosenrost** [comment]
Yes, of course the functions are deprecated, except 0xa000. But the variables are still in use.

**Comment by rosenrost** [comment]
Another example would be a TOS program that wants to determine the current cursor position. Or to work around the Falcon TOS bug which leads to permanent scrolling after the cursor has reached the bottom-right corner.

**Comment by rosenrost** [comment]
Just a reminder.

**Comment by mfro0** [comment]
(Apologies for late answer - I was a few 1000 kms away from my development machine)

Hmmm.

At a glance, this looks like an exact copy of mintlib's `mint/linea.h` include file?

If that's indeed the case, I would rather not have that in libcmini as it's unnecessary code duplication that doesn't really add value and just increases maintenance effort/cause for dubious errors if mintlib developers ever decide to change that file.

If you do serious development for MiNT, you'll most likely have mintlib includes installed anyway, so it's just a matter of adding the include path to your Makefile to gain access to the real thing?

**Comment by rosenrost** [comment]
Of course, the header file can be included from a mintlib installation. But you will need linea.c to use it (e.g. access the linea variables).

**Comment by mfro0** [comment]
> Of course, the header file can be included from a mintlib installation. But you will need linea.c to use it (e.g. access the linea variables).

I see. What if you provided the two files (plus maybe some additional example code and a README) instead in a `contrib` directory? Good enough?

**Comment by rosenrost** [comment]
Sounds not that bad. A contrib version can be found in #118.

**Comment by mfro0** [comment]
replaced by #118

**Pull request closed without merging**
