### PR TITLE
Add mintelf support

### LINKED ISSUE #117: Feature request: libcmini should be compilable with the new mintelf toolchain
The title says it all. As it doesn't use inline assembly that much, it shouldn't be too complex.

### PR DESCRIPTION
**Pull request by mikrosk**
It should also fix a few issues for the FASTCALL cases (fastcall passes/returns doubles in FPU registers for -m68881).

Fixes #117.

### CODE REVIEW

**Comment by mfro0** [comment]
Merged. Thank you!

**Comment by mikrosk** [comment]
Hmm if I try to install libcmini on a setup which does _not_ have m68k-atari-mint-gcc installed (and installing on m68k-atari-mint-elf-gcc), I get:

```
CC build/m68020-60/mshort/objs/minicrt0.o
m68k-atari-mintelf-gcc -MMD -MP -MF build/m68020-60/mshort/objs/minicrt0.d -Wall -Wstrict-prototypes -Wmissing-prototypes -Wdeclaration-after-statement -Werror -Os -fomit-frame-pointer -m68020-60 -m68020-60 -mshort -Iinclude -c sources/minicrt0.S -o build/m68020-60/mshort/objs/minicrt0.o
echo "CC build/m5475/mshort/objs/minicrt0.o"
CC build/m5475/mshort/objs/minicrt0.o
m68k-atari-mintelf-gcc -MMD -MP -MF build/m5475/mshort/objs/minicrt0.d -Wall -Wstrict-prototypes -Wmissing-prototypes -Wdeclaration-after-statement -Werror -Os -fomit-frame-pointer -mcpu=5475 -mcpu=5475 -mshort -Iinclude -c sources/minicrt0.S -o build/m5475/mshort/objs/minicrt0.o
echo make tests
make tests
for i in acctest argstest bench ctype dirent getopt malltest printf_formatting sprintf_test stdio strchr strcmp; do if test -e tests/$i/Makefile ; then make -C tests/$i COMPILE_ELF=N || { exit 1;} fi; done;
make[2]: Entering directory '/home/mikro/atari/projects/build-scripts.git/libcmini-master/tests/acctest'
rm -f depend
for d in . ./m68020-60 ./mshort ./m68020-60/mshort;\
        do m68k-atari-mint-gcc -Os -Wall -I. -I../../include -nostdlib -Iinclude -M  sources/acctest.c | sed -e "s#^\(.*\).o:#$d/objs/\1.o:#" >> depend; \
    done
sources/acctest.c:10:10: fatal error: gem.h: No such file or directory
 #include <gem.h>
          ^~~~~~~
compilation terminated.
sources/acctest.c:10:10: fatal error: gem.h: No such file or directory
 #include <gem.h>
          ^~~~~~~
compilation terminated.
sources/acctest.c:10:10: fatal error: gem.h: No such file or directory
 #include <gem.h>
          ^~~~~~~
compilation terminated.
sources/acctest.c:10:10: fatal error: gem.h: No such file or directory
 #include <gem.h>
          ^~~~~~~
compilation terminated.
mkdir -p . ./m68020-60 ./mshort ./m68020-60/mshort ./objs ./m68020-60/objs ./mshort/objs ./m68020-60/mshort/objs
echo "CC objs/acctest.o"
CC objs/acctest.o
m68k-atari-mint-gcc -Os -Wall -I. -I../../include -nostdlib -Iinclude -c sources/acctest.c -o objs/acctest.o
sources/acctest.c:10:10: fatal error: gem.h: No such file or directory
 #include <gem.h>
          ^~~~~~~
compilation terminated.
make[2]: *** [Makefile:126: objs/acctest.o] Error 1
make[2]: Leaving directory '/home/mikro/atari/projects/build-scripts.git/libcmini-master/tests/acctest'
make[1]: *** [Makefile:120: tests] Error 1
make[1]: Leaving directory '/home/mikro/atari/projects/build-scripts.git/libcmini-master'
make: *** [Makefile:184: libcmini.ok] Error 2
```
It's true that the Makefile in question contains:
```
#
# multilib flags. These must match m68k-atari-mint-gcc -print-multi-lib output
#
```
but this looks like a leftover rather than intent (i.e. force the user to have m68k-atari-mint-gcc installed even though compiling in m68k-atari-mintelf-gcc).

**Comment by mikrosk** [comment]
To be precise, I do have m68k-atari-mint-gcc installed but nothing else, so it should look for `gem.h` from mintelf and not mint sys-root.

**Comment by th-otto** [comment]
Are you sure you invoked make correctly, using COMPILE_ELF=Y? Because
`do m68k-atari-mint-gcc -Os -Wall -I. -I../../include -nostdlib -Iinclude -M  sources/acctest.c `

Seems to invoke the a.out compiler.

And yes, you have to install a newer gemlib for mintelf, as well as mintlib for mintelf (libcmini still has a few dependencies on it, like <sys/stat.h>)

**Comment by mikrosk** [comment]
It's possible that I need to change the way I build libcmini, so I'll look into that but nevertheless if it once started with m68k-atari-mintelf-gcc, it shouldn't out of the blue revert back to m68k-atari-min-gcc, IMO.

**Comment by th-otto** [comment]
Yes, but this is currently done by passing COMPILE_ELF to sub-makes. Another solution would be to include something like CONFIGVARS in all Makefiles (which would imho be better, since it also gets rid of a lot of duplicate code).

**Comment by mikrosk** [comment]
> this is currently done by passing COMPILE_ELF to sub-makes

Why can't `CROSSPREFIX` be passed to sub-makes? Now I have to introduce awkward workarounds like
```
ifeq ($(TOOL_PREFIX),m68k-atari-mintelf)
	cd libcmini-${LIBCMINI_BRANCH} \
		&& make PREFIX=${SYS_ROOT}/opt/libcmini BUILD_FAST=N BUILD_SOFT_FLOAT=N COMPILE_ELF=Y VERBOSE=yes \
		&& make PREFIX=${SYS_ROOT}/opt/libcmini BUILD_FAST=N BUILD_SOFT_FLOAT=N COMPILE_ELF=Y VERBOSE=yes install
else
	cd libcmini-${LIBCMINI_BRANCH} \
		&& make PREFIX=${SYS_ROOT}/opt/libcmini BUILD_FAST=N BUILD_SOFT_FLOAT=N COMPILE_ELF=N VERBOSE=yes \
		&& make PREFIX=${SYS_ROOT}/opt/libcmini BUILD_FAST=N BUILD_SOFT_FLOAT=N COMPILE_ELF=N VERBOSE=yes install
endif
```

**Comment by th-otto** [comment]
Why do you blame me? I didn't write the makefiles. Before the patch, submakes did not even use a mintelf toolchain at all:
https://github.com/freemint/libcmini/blob/d684a968b6ac1bb949e4cfcfd354188bdf837dd2/tests/bench/Makefile#L9
https://github.com/freemint/libcmini/blob/d684a968b6ac1bb949e4cfcfd354188bdf837dd2/tests/stdio/Makefile#L7

**Comment by mikrosk** [comment]
I'm certainly not blaming you, I was just wondering whether wouldn't be better idea to pass to sub-makes `CROSSPREFIX` instead of introducing new variable `COMPILE_ELF`. This yes/no vars make sense for fastcall or mshort (as you need to add some command line parameters) but in this case, altering `CC` is enough.

**Pull request merged**
